coverage:
  status:
    project:
      default:
        base: auto
        branches:
          - main
          - dev
          - "*/*"
        flags:
          - unit
        if_ci_failed: error
        informational: false
        only_pulls: false
        paths:
          - lib
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
  ignore:
    - "**/gen/**"
		- "**/core/**"
		- "**/features/**/data/datasources/**"
		- "**/features/**/presentation/**"
		- "**/features/**/widgets/**"
		- "**/features/**/bloc/**"
		- "**/features/**/blocs/**"
		- "**/features/**/xmodels/**"
		- "**/features/**/screens/**"
		- "**/main.dart"
