name: Analyze project

on:
  push:
    branches:
      - "*/*"

jobs:
  test:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.11"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
