name: Analyze, Build, Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Analyze project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test

  build_apk:
    needs: [test]
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm,android-arm64 --dart-define="lambiengcode=PRODUCTION" --release -v
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          name: "Waterbus ${{ github.ref_name }}"
          bodyFile: "RELEASE.md"
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
